/**
 * Voyce — Terms of Service
 *
 * Public-facing, app-owned editable content. Maintained by Voyce. Includes
 * the AI honesty disclosures so users have a single canonical reference.
 */
import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Voyce" },
      {
        name: "description",
        content:
          "The terms that govern your use of Voyce, including the limits of the AI assessment and the responsibilities of users and responders.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-[100dvh] bg-[#FAF8F5] px-5 py-10 text-[15px] leading-relaxed text-foreground">
      <div className="mx-auto max-w-2xl">
        <Link to="/" className="text-[12px] font-medium uppercase tracking-[0.14em] text-[#8A5A0E]">
          ← Back to Voyce
        </Link>
        <h1 className="mt-3 font-serif text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          This page is maintained by Voyce. Last updated: June 2026.
        </p>

        <Section title="1. Acceptance">
          By using Voyce, you agree to these terms. If you don't, please don't use the service.
        </Section>

        <Section title="2. AI assessment is advisory only">
          <p>
            Every rescue card on Voyce is generated by computer-vision AI. The AI may be
            inaccurate. Specifically, the AI <strong>cannot</strong>:
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Detect internal injuries or diseases</li>
            <li>Diagnose any medical condition</li>
            <li>Estimate exact age, weight, or breed</li>
            <li>Assess parasites, pain, pregnancy, or vaccination status</li>
            <li>Replace a veterinary examination</li>
          </ul>
          <p className="mt-3 italic">
            Always verify with a licensed veterinarian before any medical, rescue, or transport
            decision. Voyce is not liable for outcomes from acting on an AI assessment.
          </p>
        </Section>

        <Section title="3. Responder responsibility">
          Final assessments and decisions rest with rescuers and licensed vets, not with Voyce or
          its AI. Use your judgment in the field and follow local laws.
        </Section>

        <Section title="4. Sharing">
          Reports you create may be shared publicly to help mobilize the rescue network. Do not
          submit content you don't have the right to share.
        </Section>

        <Section title="5. No warranty">
          Voyce is provided "as is" without warranty of any kind. To the maximum extent permitted
          by law, Voyce disclaims all liability for any loss or harm arising from use of the
          service or reliance on AI output.
        </Section>

        <Section title="6. Changes">
          We may update these terms. Continued use means you accept the updated terms.
        </Section>

        <Section title="7. Contact">
          Questions? Reach out via the in-app help link.
        </Section>

        <div className="mt-10 text-[12px] uppercase tracking-[0.14em] text-muted-foreground">
          AI is advisory — not a diagnosis
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-6">
      <h2 className="font-serif text-lg font-semibold tracking-tight">{title}</h2>
      <div className="mt-1 text-foreground/85">{children}</div>
    </section>
  );
}
